defaults :
  - modulus_default
  - scheduler: tf_exponential_lr
  - optimizer: adam
  - loss: sum
  - _self_


jit: false
summary_histograms: true
save_filetypes : "vtk,npz"

scheduler:
  decay_rate: 0.95
  decay_steps: 8000

optimizer:
  lr: 2e-5   
  betas: [0.9, 0.999]
  
training:
  rec_validation_freq: 100
  rec_inference_freq: 100
  rec_monitor_freq: 100
  rec_constraint_freq: 100
  max_steps : 11000

custom:
  arch: "SirenArch"
  exact_continuity: False
  quasirandom: True
  adaptive_activations: True

batch_size:
  Wall: 1000
  Interior: 4000