defaults :
  - modulus_default
  - arch:
      - fully_connected
  - scheduler: tf_exponential_lr
  - optimizer: adam
  - loss: sum
  - _self_

arch:
    fully_connected:
        layer_size: 512
        nr_layers: 6

jit: false
summary_histograms: true
save_filetypes : "vtk,npz"

optimizer:
  lr: 0.001
  betas: [0.9, 0.999]
  
training:
  rec_validation_freq: 100
  rec_inference_freq: 100
  rec_monitor_freq: 100
  rec_constraint_freq: 100
  max_steps : 10000

batch_size:
  Wall: 1000
  Interior: 4000